admin (api/ui): Changes to root, functions and shared package.json to fix build error error TS2688: Cannot find type definition file for 'node'. App compiles in root and functions dirs